name = "miniapp-scafolding"
compatibility_date = "2024-08-04"

# For Cloudflare Workers
main = "worker/index.ts"

[[d1_databases]]
binding = "D1_DATABASE"
database_name = "telegram-calendar"
database_id = "349f15eb-9f90-498a-a583-7d0a298f54ff"
